### ISSUE TITLE
Include rm -rf to dist folder

### ISSUE THREAD

**Issue by ayuhito** [privatenumber/pkgroll#11]
The `dist` folder end up becoming very polluted at times, especially when you delete a source file which still leaves its bundled-up counterpart in the `dist` folder. Either cleaning up the `dist` folder by default or including a `--clean` flag would be a nice QOL addition.

(Btw, I am happy to make some PRs in the near future for some of these issues I'm making - imo this bundler is the most ideal one out of others I've seen and I'm working on integrating it into the [Fontsource](https://github.com/fontsource/fontsource) project).

**Comment by privatenumber** [comment]
`--clean-dist` flag sounds good to me!

**Comment by ayuhito** [comment]
I was working on this but privatenumber/eslint-config#33 is a blocker. Will wait till that's resolved!

**Comment by privatenumber** [comment]
Feel free to commit with linting violations via `--no-verify`.

**Comment by muratgozel** [comment]
hey hey, i need this too, will you send a pr @ayuhito ? i can figure if you arent able to. and if you still okay with this @privatenumber
