### ISSUE TITLE
Support/Allow Typescript 5 as a Peer Dependency

### ISSUE THREAD

**Issue by adaliszk** [privatenumber/pkgroll#34]
Great work on this tool! I was looking for something simpler than `tsup` and came across your simple yet powerful solution!

I have been playing around a bit, and it seems that Typescript 5 works just fine, so could we add that to the peer dependencies (like `^4.1 || ^5.0`) so that we would not get warnings about that?

I ran into this specifically with PNPM, but I assume the same warning happens in other tools.

**Comment by privatenumber** [comment]
Thank you! And for sure, happy to accept a PR!

**Comment by privatenumber** [comment]
Closed via https://github.com/privatenumber/pkgroll/pull/35
