### ISSUE TITLE
Support rollup plugins or use @rollup/plugin-strip to remove debugger statements.

### ISSUE THREAD

**Issue by kiki-kanri** [privatenumber/pkgroll#43]
### Feature request

Customize the use of the rollup plugins or use parameters (such as --strip) when executing the command to enable the @rollup/plugin-strip package.

### Motivations

Debugger statements used in development are not used in production, so I want to use the plugins to remove these debugger statements.

Whether to support the use of additional configuration files to customize the rollup plugins?

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
I'm not sure how common it is for devs to want to produce distribution code while still having `debugger` in the source and auto stripping it. Is there a precedent of bundlers supporting this?

Regarding customization, this tool basically configures Rollup for you so I'd like for it to export a function so users can configure Rollup too. Something like:

rollup.config.js
```ts
import { inferConfig } from 'pkgroll'

export default extendConfig({
	plugins: [
		// ...
	]
})
```

**Comment by kiki-kanri** [comment]
When I think about it, it's not very common to include a debugger in the class or function to be export, so this feature may not be needed.

However, it may be possible to set plugins or other parameters using a custom rollup config in future, which is optional and works fine without rollup.config.js in file list.

Incidentally, when will you merge this [PR](https://github.com/privatenumber/pkgroll/pull/41) and release a new version?

**Comment by privatenumber** [comment]
Oh yeah, I dropped the ball on that one. It requires a breaking change release but I'll try to pick it up soon.

**Comment by taernsietr** [comment]
Also interested in this. pkgroll seems to ignore rollup.config.js and I couldn't find any API to extend the default derived setup :(

**Comment by kiki-kanri** [comment]
> Also interested in this. pkgroll seems to ignore rollup.config.js and I couldn't find any API to extend the default derived setup :(

I'm not currently using this package, I'll reopen this issue if I confirm that I need this feature.

**Comment by pjeby** [comment]
I personally switched to [tsup](https://tsup.egoist.dev/) for projects with more complex needs, and only use pkgroll for builds that don't need customization.
