### ISSUE TITLE
feat: tsconfig paths support

### ISSUE THREAD

**Issue by mjgerace** [privatenumber/pkgroll#48]
### Feature request

I understand that `pkgroll` is based off of package.json config - however, it would be really nice to have a build system that operates exactly like tsx. I use `tsx` for dev, since the watch/file execution is the fastest i've found by far. However, this means that I must use something like tsup, or ts-node for actual production building.

This is a concern for me, as tsx auto-configures, but these other libraries do not. I want as few deviations as possible between my dev environment with tsx and the production build for obvious reasons - I want a similar output format, build process, etc to reduce the chance of production-build-only bugs.

One major way to close this gap is to support tsconfig paths. Today, wildcard matching paths isn't possible with package.json.

### Motivations

Closing the gap between my dev and full build process.

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Yeah I agree, alias support via tsconfig.json would be great! pkgroll is about zero-config by leveraging existing configurations.

PR welcome

**Comment by samal-rasmussen** [comment]
Ah. I have two entries in my paths:
```
"services/*": ["./src/services/*"],
"shared/*": ["./src/shared/*"]
```

And now trying pgkroll I get a lot of errors like this:
`
"shared/models/product.model" is imported by "src/db/product.db.ts", but could not be resolved – treating it as an external dependency.
`
I've been running with tsx, but wanted to do bundling now because of some infrastructure limitations. I will try Rollup.

**Comment by olee** [comment]
Is there even any way to get this working right now by using package.json imports configuration with full directories? Because it seems that imports only supports singlular files.

**Comment by error-four-o-four** [comment]
Sorry for any inconvenience caused by my lack of experience and thank you for your work.
It works like a charm

**Comment by privatenumber** [comment]
No inconvenience at all! Really appreciate your contribution—hope to see you contribute again! Thanks

**Comment by alwyntan** [comment]
Hi, was just digging around this issue and I couldn't get it to work. Are there any other configurations needed to make it work? My package.json does not contain an `imports` field. @error-four-o-four @privatenumber 

my tsconfig for paths: 
```
{
    "baseUrl": "./",
    "paths": {
      "#/*": ["src/*"]
    },
}
```

The error when running `npx pkgroll`:

```
Could not resolve import "#/config" in /src/server.ts using imports defined in package.json. Invalid import specifier.
"#/config" is imported by "src/server.ts", but could not be resolved – treating it as an external dependency.
```

**Comment by privatenumber** [comment]
Try following the tests added in the PR for reference. And if it's still not working, you can file a bug report with a minimal reproduction.

**Comment by alwyntan** [comment]
Thanks. I did some testing and it didn't work, but I found out why.

Turns out, using `#` as an alias with pkgroll doesn't work, not sure if that is intended, using other symbols like `@` or `$` works.

**Comment by privatenumber** [comment]
Ooh gotcha. It's because Node.js subpaths import (which should be used instead of tsconfig.json paths btw) have a requirement to start with `#`.

Would you mind filing a bug report for that? It should be fixed

**Comment by alwyntan** [comment]
Yup of course, here's the bug report #106
