### ISSUE TITLE
shims for __dirname so one code can output to both esm and cjs

### ISSUE THREAD

**Issue by wighawag** [privatenumber/pkgroll#61]
### Feature request

shim for _dirname or other features like this

This is something tsup supports (and esbuild) : https://github.com/egoist/tsup/blob/00188a0dc848c48fac45de245d1e021f370a84a3/src/cli-main.ts#L91

### Motivations

My project export to both cjs and esm and being able to use the same code for both is needed

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
You mean you'd like to use `__dirname` in ESM? 

CommonJS is being phased out by Node in favor of the ESM standard, so it might be better to shim `import.meta.url` for CJS. I haven't tested yet but this might even work in CJS already.

**Comment by wighawag** [comment]
I ended up using the following

```ts
import {dirname} from 'path';
import {fileURLToPath} from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
```

and it indeed seems to be working

in the cjs it get transformed into :

```
path.dirname(url.fileURLToPath((typeof document === 'undefined' ? require('u' + 'rl').pathToFileURL(__filename).href : (_documentCurrentScript && _documentCurrentScript.src || new URL('index.cjs', document.baseURI).href))));
```

So I guess this works, not sure why it is that verbose though

**Comment by privatenumber** [comment]
There are more concise options: https://stackoverflow.com/questions/46745014/alternative-for-dirname-in-node-js-when-using-es6-modules

```js
const __dirname = import.meta.dirname;
const __filename = new URL('', import.meta.url).pathname;
const __dirname = new URL('.', import.meta.url).pathname;
```

Anyway, closing as `import.meta.url` should be used.

**Comment by diego-lipinski-de-castro** [comment]
Why I am getting this when compilling

```javascript
const import_meta = {};
const __filename = fileURLToPath(import_meta.url);
const __dirname = dirname(__filename);
```

**Comment by 0xdevalias** [comment]
> Why I am getting this when compilling
> 
> const import_meta = {};
> const __filename = fileURLToPath(import_meta.url);
> const __dirname = dirname(__filename);
> Code
> 
> const __filename = fileURLToPath(import.meta.url);
> const __dirname = dirname(__filename);

@diego-lipinski-de-castro See the following:

- https://github.com/privatenumber/pkgroll/issues/115

Or for a deeper dive into the reasons why, my answer here:

> FYI: I did a bit of a deepdive/writeup of the underlying aspects/specifics of this in this StackOverflow answer:
> 
> - https://stackoverflow.com/questions/77212131/prettier-createrequire-the-argument-filename-must-be-a-file-url-object-file/79471727#79471727
> 
> Which I also [made a gist of](https://gist.github.com/0xdevalias/37a189cac102ff53d5c8f10357ac6a83#deep-dive-into-importmeta-support-in-pkgroll--esbuild) for posterity, and shared on my relevant socials ([1](https://x.com/_devalias/status/1894999383890071723), [2](https://bsky.app/profile/devalias.net/post/3lj5bp4wxdc2t), [3](https://www.linkedin.com/posts/glenn-devalias-grant_prettier-createrequire-the-argument-filename-activity-7300766878421987330-EZAi/)) 
>
> _Originally posted by @0xdevalias in [#115](https://github.com/privatenumber/pkgroll/issues/115#issuecomment-2687066662)_
