### ISSUE TITLE
__dirname pouring in mjs files

### ISSUE THREAD

**Issue by ZeldOcarina** [privatenumber/pkgroll#80]
### Problem

After I try to run an mjs bundle I am getting the usual __dirname error:

```
ReferenceError: __dirname is not defined in ES module scope
    at file:///Users/mattiarasulo/web-development-desktop.nosync/call-center-directory/dist/index-DiusTozJ.mjs:115:25
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:485:26)
    at async main (file:///Users/mattiarasulo/web-development-desktop.nosync/call-center-directory/dist/server-BEW9aa65.mjs:46152:66)
```

By checking the bundled code I see __dirname is used extensively, this is where the stack trace is leading to:

`const { parse: parse$j, parseAsync, xxhashBase64Url, xxhashBase36, xxhashBase16 } = requireWithFriendlyError(
	existsSync(path$n.join(__dirname, localName)) ? localName : `@rollup/rollup-${packageBase}`
);`

I'm unsure if this is a bug with pkgroll or upèstream with esbuild. 

### Expected behavior

.mjs files should not have __dirname or a shim should be automatically included.

### Minimal reproduction URL

https://github.com

### Version

v2.4.2

### Node.js version

v22.5.1

### Package manager

npm

### Operating system

macOS

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
As with any issue, we have to validate that it's a pkgroll bug first with a minimal reproduction to align and allow contributors to debug independently.

**Comment by ZeldOcarina** [comment]
Hi, I'm sorry here's the repro:
https://github.com/ZeldOcarina/pkgroll-repro

**Comment by privatenumber** [comment]
Please remove everything unnecessary to demonstrate that the bug is in pkgroll.

**Comment by ZeldOcarina** [comment]
I wouldn't know how to reproduce by removing stuff sorry.. :(
Anyways I've switched to Vite for now and I made it work that way. If you can take a closer look, otherwise please close.
