### ISSUE TITLE
Allow externalizing dependencies even if they are only defined in devDependencies

### ISSUE THREAD

**Issue by danielpza** [privatenumber/pkgroll#86]
### Feature request

Allow externalizing dependencies even when they are only listed as `devDependencies`. Possibly through a flag `--force-external <deps>`

### Motivations

I have some peer optional dependencies in a package that I want to exclude from the bundle. The problem is I cannot use optional or peer dependencies as npm/yarn/pnpm install them by default. So I ended up removing them from optional/peer dependencies and left them listed only as devDependencies.

The package in question is [vitest-mms](https://github.com/danielpza/vitest-mms), see [package.json](https://github.com/danielpza/vitest-mms/blob/master/package.json). It provides exports depending on if the user is using `mongodb` or `mongoose.` The user is not expected to install both of these dependencies, only the one it will work with. For example if they are only using `mongodb` they are not expected to install `mongoose`.

The problem is pkgroll would bundle `mongodb` and `mongoose` dependencies since they would be only listed as `devDependencies` (https://github.com/danielpza/vitest-mms/commit/e28b21e)

### Alternatives

Something like tsup's `--external` flag https://tsup.egoist.dev/#excluding-packages

### Additional context

- https://tsup.egoist.dev/#excluding-packages
- https://github.com/danielpza/vitest-mms

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
For optional peer dependencies, you should use [`peerDependenciesMeta`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta). If you specify `optional` there, the package managers should not install them.

**Comment by danielpza** [comment]
Thank you!! I must have missed it. This should solve my issue.
