### ISSUE TITLE
Support export platforms

### ISSUE THREAD

**Issue by yeliex** [privatenumber/pkgroll#87]
### Feature request

Support export platforms, for example

```json
// package.json 
{
    "exports": {
        "./": {
            "node": "./dist/index.node.js",
            "browser": "./dist/index.browser.js"
        }
    }
}
```

### Motivations

It is important for modules supports both node and browser but have some platform specifics.

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Isn't this already possible? What specifically is missing?

**Comment by yeliex** [comment]
@privatenumber I have created a minimal re-production to better describe my request
https://github.com/yeliex/pkgroll-multi-platform

 the main reason is that `pkgroll` use export keys as generated name, not the actually file path in the exports field?

**Comment by yeliex** [comment]
@privatenumber https://github.com/privatenumber/pkgroll/blob/df8668bd0a44fa5aedfd755131fcbeffb13e7b72/src/utils/get-rollup-configs.ts#L265 it is better to use `path.basename` to get filename without extension?  i would create a pr to fix this
