### ISSUE TITLE
Single quoted in import aren't replaced with double quotes

### ISSUE THREAD

**Issue by rtritto** [privatenumber/pkgroll#94]
### Problem

After run `yarn pkgroll`, the file
```ts
// /src/index.mjs
import path from 'node:path'
console.log('sep', path.seph)
```

is builded with import path having single quoted instead of double quotes.
```ts
// /dist/index.mjs
import path from 'node:path';

console.log("sep", path.seph);
```

### Expected behavior

```ts
// /dist/index.mjs
import path from "node:path";

console.log("sep", path.seph);
```

### Minimal reproduction URL

https://github.com/rtritto/test-pkgroll/tree/bug-quotes

### Version

2.5.0

### Node.js version

22.9.0

### Package manager

yarn

### Operating system

Windows

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Sorry, I'm confused—how is this a bug?

**Comment by rtritto** [comment]
Build contains mixed quotes (`'` and `"`).

Source:
```ts
// /src/index.mjs
import path from 'node:path'
console.log('sep', path.seph)
```
Dist:
```diff
// /dist/index.mjs
- import path from 'node:path'  // current
+ import path from "node:path"  // expected
console.log("sep", path.seph)
```

The `'` in _imports_ should be replaced with `"` at same way of code below imports.

**Comment by privatenumber** [comment]
Okay, but why is this a bad thing? Is this breaking your code?

**Comment by rtritto** [comment]
> Okay, but why is this a bad thing? Is this breaking your code?

It's bad because it's mixed, so it breaks for example with a search.

As standards and with other similar libraries, the `"` is always used.

**Comment by privatenumber** [comment]
It's valid JS.

If you have a preference for specific quote styles in your output, I recommend running it through Prettier or ESLint for formatting.

Alternatively, you can use a quote-style agnostic regex search like this: `(["']).+?\1`.
